drop table if exists accounts;

create table accounts (
    id int generated by default as identity,
    name varchar(100) not null,
    balance dec(15,2) not null,
    primary key(id)
);

insert into accounts(name,balance)
values('Bob',10000);

insert into accounts(name,balance)
values('Alice',10000);

create or replace procedure transfer_money(sender int, receiver int , amount dec)
language plpgsql as
$$
begin

update accounts 
set balance = balance - amount 
where id = sender;

IF NOT FOUND THEN
	RAISE EXCEPTION 'Sender account % does not exist', sender;
END IF;

update accounts
set balance = balance + amount
where id = receiver;

IF NOT FOUND THEN
	RAISE EXCEPTION 'Receiver account % does not exist', receiver;
END IF;


commit;
	-- EXCEPTION
 --        WHEN OTHERS THEN
 --            -- Rollback the transaction in case of any error
 --            ROLLBACK;
 --            -- Re-raise the exception to propagate the error
 --            RAISE;
	-- END;
end;
$$

call transfer_money(1,56,200);

select * from accounts;